### ISSUE TITLE
Choisir une licence pour l’application

### ISSUE THREAD

**Issue by emchateau** [EcrituresNumeriques/sensPublicApp#1]
[SynopsX](http://synopsx.github.io) est développé sous licence publique générale [GNU 3.0](https://www.gnu.org/licenses/licenses.html#GPL) ou supérieure.

Le plus simple serait de choisir cette Licence pour les développements à effectuer pour la Webapp de Sens-Public. Mais je ne sais pas si une politique générale de Licence a été adoptée par la Chaire de recherche.

**Comment by lakonis** [comment]
On garde la GNU 3. Si comptatible avec BaseX, mais j'imagine que oui.

**Comment by emchateau** [comment]
J’allais réouvrir pour l’avis de Marcello (mais Nicolas = Marcello ;)

**Comment by lakonis** [comment]
oui je suis allé un peu vite, mais comme on a discuté de politique de license récemment avec Marcello, voilà. Gnu 3. :)
