### ISSUE TITLE
Créer une instance BaseX sur le serveur

### ISSUE THREAD

**Issue by emchateau** [EcrituresNumeriques/sensPublicApp#2]
Courriel de @lakonis du 2017-01-13, 14h50 :

Bonjour Timothée,
pour te mettre au courant, le département d'info ne pourra pas héberger notre serveur finalement, donc on va essayer de faire du forcing auprès du service technique de l'université pour avoir un accès internet décent chez nous. Mais j'anticipe que ca ne sera pas pour tout de suite.
Donc, restons sur notre serveur OVH.ca pour le moment.

Outre un owncloud (décision à prendre), nous aurons rapidement besoin d'une install de SynopsX dans un nouveau docker. On aura besoin de pouvoir développer/tester, et à terme (ou progressivement ?) de déployer sur une url à définir. Emmanuel en copie a co-développé SynopsX, donc si nécessaire vous pouvez dialoguer sur la config du docker.
On a une réunion le 1er février avec Emmanuel pour mettre en place la base (XML), un début d'API, et un site test associé.

Je mets aussi Arthur en copie pour la partie serveur OVH. Il faut que vous échangiez sur ce qu'Arthur a déjà mis en place et que tu réfléchisses à des scénarios d'évolution/sécurisation. Il y a peut-être une remise à plat à faire, mais attention, une bonne partie des dockers en place sont des sites en production, donc il faut que ca tourne :)
Il nous manque clairement un serveur, on croise les doigts pour celui de l'université. A voir ce qui est possible de faire de ton côté Timothée en attendant une architecture plus confortable.
Je laisse Arthur te créer un accès ssh au ovh et te briefer sur son install des dockers, les backups de chacun etc.

Je crois que c'est tout pour le moment.

A disposition pour clarifier.

bien à tous,
nicolas.

**Comment by emchateau** [comment]
Salut, 
Je ne connais pas l’environnement de développement actuel ni votre configuration. Quelques précisions concernant SynopsX, ci-dessous.

[SynopsX](https://synopsx.github.io) est une application XQuery développée avec la base de données XML native, libre et open source, [BaseX](http://basex.org).

[BaseX](http://basex.org) s’exécute en environnement Java (version > 8.0 requise). L’application s’exécute avec le conteneur de servlet [Jetty](http://www.eclipse.org/jetty/) ce qui permet un déploiement aisé.

Dans l’idéal, il faudrait une machine virtuelle avec Java dans laquelle serait installé BaseX. Nous avons besoin de la distribution complète de BaseX qui doit être exécuté en mode serveur HTTP.

L’application peut être directement connectée sur l’Internet pour commencer. C'est une configuration relativement sécuritaire. Pour renforcer la sécurité, l’application peut être placée derrière un proxy http.

Emmanuel

**Comment by timoguic** [comment]
Salut,

Je ne connais également pas très bien la configuration actuelle mais je regarde dès que j'ai accès. Je ne pense pas qu'il y ait grand chose à changer, simplement réorganiser l'existant et l'améliorer.
@emchateau : est ce que ça peut tourner dans un container Docker? J'ai cru comprendre que c'était un peu le standard pour le déploiement des applications de la chaire.

Dans l'idéal je pense qu'il faudrait que l'on ait un reverse proxy qui connecte et serve tous les sites qui tournent dans leurs dockers réciproques.

@lakonis quand tu dis qu'il manque un serveur, c'est pour quelle raison exactement? Je peux regarder de mon côté mais je n'ai rien de vraiment fiable qui pourrait être utilisé en production à l'heure actuelle. Quid du serveur d'Arthur en France?

Bien à vous,
- Tim

**Comment by emchateau** [comment]
Je ne connais pas vraiment Docker. Les applications Java n’ont habituellement pas besoin de compilation et sont directement exécutables par l’intermédiaire d’un conteneur de servlet (ici Jetty qui prend en charge le serveur web). Mais je n’ai pas l’impression qu’il y ait de contre-indication pour Docker qui pourrait prendre en charge le déploiement complet.

Il y a trois manières de déployer une application avec BaseX :
- comme une application standalone en exécutant BaseX HTTP Server
- comme un servlet web dans un Servlet Container
- comme un servlet web avec Maven
cf. http://docs.basex.org/wiki/Web_Application

La solution qui a été retenue par la TGIR Huma-Num pour le déploiement d’applications avec BaseX a plutôt été, à ma connaissance, de créer une machine virtuelle avec Java et BaseX qui puisse être répliquée pour la création de chaque instance sur leur grille de service. Les applications sont publiées en standalone en exécutant BaseX HTTP Server. Si on part sur cette solution, je déconseille vraiment Tomcat qui est beaucoup trop lourd à gérer en comparaison de la simplicité de Jetty. (pour cette distribution c'est le zip complet qu’il faut télécharger)

La documentation de BaseX contient une page sur l’utilisation de Docker http://docs.basex.org/wiki/Docker

J'imagine que cela impliquera également une suite d’instructions pour installer SynopsX dans BaseX et le répertoire git ici présent pour construire l’application : avant de démarrer BaseX en mode serveur : cloner https://synopsx.github.io dans `webapp/` puis cloner ce répertoire dans `webapp/synopsx/workspace/`, ou faire des liens symboliques.

**Comment by timoguic** [comment]
@emchateau merci beaucoup pour les liens et les informations supplémentaires, très utile.
D'après ce que je vois il y a une image Docker sur le repository 'officiel' donc le déploiement devrait s'en trouver très largement facilité. Le schéma de déploiement que tu mentionnes fonctionnera bien aussi sous ce modèle, donc je pense qu'il va falloir explorer par là.

@lakonis dès que j'ai accès au serveur OVH.ca je me lance!

**Comment by emchateau** [comment]
Just in case, il y a une issue chez BaseX concernant le Docker file : https://github.com/BaseXdb/basex/issues/1406

**Comment by timoguic** [comment]
@emchateau Pourrais tu clarifier comment fonctionne BaseX et sa relation avec BaseX DB? J'ai commencé à lancer une instance BaseX comme indiqué dans la doc, mais le lien que tu as envoyé référence BaseXdb, qui semble être quelque chose d'autre?

Également tu parles de cloner SynopsX dans webapp - où est ce dossier exactement dans l'arborescence? Je ne le vois pas dans le Docker standard de BaseX.

Merci!

**Comment by emchateau** [comment]
J’ai pris l’issue concernant le docker file sur le repo GitHub de BaseX, donc il s’agit bien du même logiciel.
Par contre je ne sais pas comment le fichier est distribué sur docker car il y a plusieurs distributions de BaseX cf. http://basex.org/products/download/all-downloads/

Habituellement j’utilise l’Archive Zip qui contient les exécutables pour Jetty et tous les scripts d’exécution dans `bin/`.

Le `Core Package` ne contient pas tout cela, et c’est peut-être le problème que tu rencontres en déployant avec docker. Ce Core Package ne propose qu’une archive Jar qui est l’exécutable de BaseX. 

L’arborescence que j’utilise est l’arborescence par défaut de BaseX. Comme tu peux la voir dans l’archive zip :
- basex
|-- data
|-- repo
|-- ...
|-- webapp 

Je donne cours aujourd’hui, mais je vais regarder un peu comment marche le déploiement avec Docker pour te répondre plus précisément.

**Comment by timoguic** [comment]
Merci @emchateau, je vais aussi regarder un peu plus précisément comment fonctionne Docker. Je sais que tu avais parlé de Jetty mais je n'ai rien trouvé sur l'instance que j'ai téléchargé depuis la forge Docker. Une solution pourrait être de construire notre propre instance Docker, qui construit une instance BaseX et rapatrie les sources de SynopsX. Je continue à expérimenter et on se tient au courant.

**Comment by emchateau** [comment]
Ok. N’hésites pas à télécharger l’archive zip pour faire tes tests. Il faut simplement Java8 pour la faire tourner.
Je vais regarder de mon côté, car je n’ai jamais vraiment considéré l‘hypothèse de packager l’application comme c’est proposé dans les différentes modalités de déployer une application http://docs.basex.org/wiki/Web_Application
