### ISSUE TITLE
Définir le scheme de l’API

### ISSUE THREAD

**Issue by emchateau** [EcrituresNumeriques/sensPublicApp#5]
Définir les points d’entrée de l’API et les contenus produits à partir des articles

**Comment by lakonis** [comment]
# Scheme URI
points d'entrée API

## liste des articles par type d'article
  path: /typeArticle/
  param:
    - typeArticle: parmi {essai, chronique, entretiens, lecture}

## liste des articles par dossier thématique
  path: /dossier/:idDossier/
  param:
    - idDossier: ID parmi {famille de mot-clé "textes regroupés" ou rubrique:109 "Dossier" }
    - récupère tous les articles + l'article sommaire en premier

## liste des dossiers
  path: /dossier/
  param:


## liste des articles par auteur
  path: /auteur/:idAuteur
  param:
    - idAuteur: ID

## liste des articles par thématique
  path: /thematique/:idThematique
  param:
    - idThematique: ID {famille de mot-clé Thématique, attribut à ajouter dans la balise <descripteur>}

## liste des articles par région
  path: /region/:idRegion
  param:
    - idRegion: ID {famille de mot-clé Région, attribut à ajouter dans la balise <descripteur>}

## liste des articles par auteur cité
  path: /auteur-cite/:idAuteurcite
  param:
    - idAuteurcite: ID {famille de mot-clé Auteur cité, attribut à ajouter dans la balise <descripteur>}

## liste des articles par média
  path: /media/:idMedia
  param:
    - idMedia: ID {famille de mot-clé Media + Domaine artistique, attribut à ajouter dans la balise <descripteur>}

## liste des articles par mot-clés
  path: /motcle/:idMotcle
  param:
    - idMotcle: ID {famille de mot-clé "Regroupement Thématique", attribut à ajouter dans la balise <descripteur>} + balise <grmotcle> + mot-clé libre}

## liste des articles par date
  path: /date/YYYY
  param:
    - si YYYY : tous les articles de l'année YYYY

## article
  path: /idArticle/
  param:
    - idArticle: ID

**Comment by lakonis** [comment]
@emchateau  voir doc/schemaURI.md ca sera plus simple.
