### ISSUE TITLE
Mettre en place un déploiement automatisé via Docker

### ISSUE THREAD

**Issue by timoguic** [EcrituresNumeriques/sensPublicApp#6]
Afin de pouvoir facilement travailler avec différentes instances et comme discuté récemment, il faudrait définir les actions et étapes à faire pour déployer une instance BaseX / SynopsX propre et conforme aux besoins. Pour le moment, nous avons:
- base Ubuntu 16.04
- OpenJDK 8
- copie du repository synopsx dans /data (à changer)
- mise en route du script install.sh du repository (à améliorer)
- lancement de basex (via le binaire basexhttp)

**Comment by emchateau** [comment]
Une fois l’environnement déployé (Ubuntu et OpenJDK), je dirais :
1. Téléchargement de la release de BaseX (elles sont très fréquentes, une par trimestre environ)
2. Copie des sources de SynopsX (git...)
3. Copie des sources de sensPublicApp (git...)
4. Création des liens symboliques
```bash
ln -s blabla/basex/webapp data/synopsx
ln -s blabla/basex/webapp/synopsx/workspace/sp data/sensPublicApp # ! le repo dans workspace doit être nommé "sp"
```
6. peut être du boulot à faire pour configurer Jetty qui est shipé dans BaseX pour définir l’adresse sur laquelle c’est servi car sinon c’est en localhost:xxxx. Mais cela dépend de l’architecture que tu envisages pour la connexion sur l’internet
7. lancement du script basex/bin/basexhttp
8. Il y a sans doute quelque chose à prévoir pour charger les données XML. Cela peut être une commande à la base de données qui dispose d’un client en ligne de commande
Pour refaire l’installation sans écraser les données, on peut aussi avoir les données stockées à part, car le chemin du répertoire data/ est configurable dans BaseX et ils ne changent habituellement pas leur structure de données.

**Comment by timoguic** [comment]
Hello,

J'ai avancé un peu sur ce point.

> Téléchargement de la release de BaseX (elles sont très fréquentes, une par trimestre environ)

Fait - il n'y a pas d'adresse automatique pour la dernière version (à moins d'utilliser latest qui est un snapshot pour développeurs) donc pour mettre à jour BaseX il faudra mettre à jour la version du fichier dans le Dockerfile.

> Copie des sources de SynopsX (git...)
> Copie des sources de sensPublicApp (git...)

Fait.

> Création des liens symboliques

Fait aussi - je pense que l'exemple que tu as donné était inversé.

> peut être du boulot à faire pour configurer Jetty (...) car sinon c’est en localhost:xxxx

Ca ne pose pas de problème pour le moment, on peut exposer les ports avant de les mettre derrière un reverse proxy.

> lancement du script basex/bin/basexhttp

Fait, mais il n'y a pas grand chose qui se passe :-)

> Il y a sans doute quelque chose à prévoir pour charger les données XML. Cela peut être une commande à la base de données qui dispose d’un client en ligne de commande

Plus précisément?

> Pour refaire l’installation sans écraser les données, on peut aussi avoir les données stockées à part, car le chemin du répertoire data/ est configurable dans BaseX et ils ne changent habituellement pas leur structure de données.

Ca serait intéressant. Comment on fait? Les données doivent être stockées de manière persistente en dehors du Docker de manière à faciliter les backups et la reprise d'activité etc.

Là où j'en suis: j'ai un BaseX qui écoute sur le port 8984.
```
Stopped at /src/basex/webapp/restxq.xqm, 17/12:
[bxerr:BASX0003] Path "" assigned to several functions:
/src/basex/webapp/restxq.xqm, 17/12
/src/basex/webapp/synopsx/_restxq/webapp.xqm, 59/10
```

**Comment by emchateau** [comment]
Super merci !

En effet, j’ai probablement inversé la commande pour les liens symboliques.

En ce qui concerne le téléchargement de la dernière version des sources, veux-tu que je demande sur la liste ? Christian de BaseX répond très vite habituellement.

L’exécution du script `basexhttp` ne fait qu’exécuter BaseX et rendre l’application disponible en mode serveur. L’adresse de ce serveur et son port sont configurables avec `basex/webapp/WEB-INF/jetty.xml`. Il faudra probablement renseigner une adresse IP et personnaliser le port, et j’avais omis cette étape qui ne se pose pas vraiment en local.

Il y a plusieurs manières de charger les données dans BaseX. 
- BaseX est livré avec une interface web sommaire nommée dba qui est accessible en mode serveur sur l’adresse (en local) `http://localhost:8984/dba/` On peut l’utiliser pour charger les données, etc.
- En mode serveur on peut également exécuter des requêtes REST pour charger des fichiers (il s’agit alors de commandes rédigées en XQuery que je peux t’écrire).
- On peut également démarrer BaseX en ligne de commande (avec le script `bin/basex`)pour lui passer une commande (en XQuery ou dans un langage de commande de base de données non normalisé). 

En fait on a sans doute sauté l’étape des mots de passes, etc. En démarrant BaseX comme on le fait, la base fonctionne avec les mots de passe par défaut. Pour la sécurité, il faudrait sans doute modifier ces mots de passe. De même, il serait sans doute préférable pour des raisons de sécurité de désactiver certaines fonctionnalités REST.

Je te reviens sur ça ainsi que sur la manière de configurer le répertoire data, il faut que je fasse quelques tests. C'est simplement spécifié dans un des fichiers `.basex` que créé BaseX lors du lancement s’ils n’existent pas. On peut aussi installer BaseX avec un de ces fichiers de config.

**Comment by timoguic** [comment]
> En ce qui concerne le téléchargement de la dernière version des sources, veux-tu que je demande sur la liste ? Christian de BaseX répond très vite habituellement.

C'est comme tu le sens. Je ne trouve pas ça logique de ne pas avoir de version fixe pour un déploiement, sinon ça veut dire qu'on peut upgrader sans s'en rendre compte. Si tu penses que ça ne pose pas de problème, on peut demander à avoir un lien latest-stable par exemple.

> En fait on a sans doute sauté l’étape des mots de passes, etc. En démarrant BaseX comme on le fait, la base fonctionne avec les mots de passe par défaut. Pour la sécurité, il faudrait sans doute modifier ces mots de passe. De même, il serait sans doute préférable pour des raisons de sécurité de désactiver certaines fonctionnalités REST.

J'ai essayé de changer USER et PASSWORD dans .basex mais ça n'a pas l'air d'avoir changé grand chose (invalid login data). Des instructions de ta part sur ce point seront les bienvenues :)

**Comment by timoguic** [comment]
Quel est le statut sur le projet BaseX / SynopsX?
De mon côté j'ai mis au propre la configuration du container, ainsi que du container d'administration DBA. Il tourne sur le port 18984, et semble fonctionnel. Le container SynopsX présente toujours les mêmes messages d'erreur sur la page d'accueil: 

Stopped at /srv/BaseXWeb/synopsx/mappings/htmlWrapping.xqm, 168/33:
[bxerr:BXSL0001] Compiler warnings:
  line 4: Illegal attribute 'xpath-default-namespace'.
ERROR:  'Could not compile stylesheet'
FATAL ERROR:  'Error checking type of the expression 'funcall(matches, [step("self", -1), literal-expr(^\s)])'.'
           :Error checking type of the expression 'funcall(matches, [step("self", -1), literal-expr(^\s)])'.

Stack Trace:
- /srv/BaseXWeb/synopsx/models/synopsx.xqm, 168/49
- /srv/BaseXWeb/synopsx/_restxq/synopsx.xqm, 86/43

**Comment by timoguic** [comment]
Je viens de vérifier /synopsx/config et l'application par défaut sélectionnée est SynopsX, ce qui est je pense correct. Peut être une autre idée?

**Comment by lakonis** [comment]
Il faut créer le projet "sp" (bouton `créer`) et sélectionner sp comme projet par défaut.

**Comment by emchateau** [comment]
Salut Tim,

Il faudrait que tu rétablisses le lien symbolique vers SynopsX qui a été supprimé.
Dès que tu as rétabli le lien symbolique vers SynopsX je m’en occupe. Nous avons identifié le pb avec Nicolas après notre entretien, et c'est simplement qu’il faut créer la base de SynopsX.

Pour voir si cela fonctionne je vais faire la manip dans l’interface graphique. Mais pour le déploiement, je vais préparer la requête XQuery qui créée le projet pour ne pas être confronté à ce problème par la suite.

Je pense aux Users, désolé je suis à la bourre sur plein de trucs.

Emmanuel

**Comment by timoguic** [comment]
Hello à tous,

J'ai mis à jour l'instance comme j'ai vu que des mises à jour avaient été faites sur les repository git.
Ca m'envoie maintenant sur /sp, et il n'y a plus de message d'erreur. Je ne pense pas pouvoir assister à grand chose de votre discussion cet après midi - je serai bien occupé aujourd'hui :(
Si il y a quoi que ce soit vous pouvez me Slacker - je serai dispo en asynchrone.
